language: java

jdk:
  - oraclejdk8
  
notifications:
  email: false
  
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  ./gradlew build
